create table conditions (
   latitude real not null,
   longitude   real not null,
   elevation   real not null,
   station_id  text not null,
   observation_epoch integer not null,
   local_epoch integer not null,
   local_tz_offset   integer not null,
   weather  text not null,
   temp_c   real not null,
   relative_humidity real not null,
   wind_degrees   real not null,
   wind_kph real not null,
   wind_gust_kph  real not null,
   pressure_mb real not null,
   pressure_trend real not null,
   dewpoint_c  real,
   heat_index_c   real,
   windchill_c real,
   visibility_km  real not null,
   solarradiation real not null,
   UV real not null,
   precip_1hr_metric real not null,
   precip_today_metric  real not null,
   primary key (station_id, observation_epoch)
);